// global_data.dart
List<Map<String, String>> friendList = [
  {'name': 'Gamer42', 'image': 'assets/images/avatar1.jpg'},
  {'name': 'Beautyeve', 'image': 'assets/images/avatar2.jpg'},
  {'name': 'Liya James', 'image': 'assets/images/avatar3.jpg'},
  {'name': 'Gamer65', 'image': 'assets/images/avatar4.jpg'},
  {'name': 'Beautyeve', 'image': 'assets/images/avatar5.jpg'},
  {'name': 'Liya James', 'image': 'assets/images/avatar6.jpg'},
  {'name': 'Gamer65', 'image': 'assets/images/avatar7.jpg'},
  {'name': 'Beautyeve', 'image': 'assets/images/avatar8.jpg'},
  {'name': 'Liya James', 'image': 'assets/images/avatar9.jpg'},
];

final List<Map<String, dynamic>> allProducts = [
  {
    'id': 1,
    'image': 'assets/images/c1.jpg',
    'brand': 'H&M',
    'title': 'Regular Fit Cashmere Jumper',
    'price': 3199,
    'original': 7999,
    'discount': '60% OFF',
    'category': 'clothing',
    'gender': 'men',
    'type': 'sustainable',
  },
  {
    'id': 2,
    'image': 'assets/images/c2.jpg',
    'brand': 'Zara',
    'title': 'Eco Cotton Shirt Dress',
    'price': 2799,
    'original': 6999,
    'discount': '50% OFF',
    'category': 'clothing',
    'gender': 'women',
    'type': 'sustainable',
  },
  {
    'id': 3,
    'image': 'assets/images/c1.jpg',
    'brand': 'H&M',
    'title': 'Regular Fit Cashmere Jumper',
    'price': 3199,
    'original': 7999,
    'discount': '60% OFF',
    'category': 'clothing',
    'gender': 'men',
    'type': 'sustainable',
  },
  {
    'id': 4,
    'image': 'assets/images/b3.jpg',
    'brand': 'EcoBag',
    'title': 'Vegan Leather Tote',
    'price': 2149,
    'original': 4299,
    'discount': '50% OFF',
    'category': 'bags',
    'gender': 'women',
    'type': 'sustainable',
  },
  {
    'id': 5,
    'image': 'assets/images/c1.jpg',
    'brand': 'H&M',
    'title': 'Regular Fit Cashmere Jumper',
    'price': 3199,
    'original': 7999,
    'discount': '60% OFF',
    'category': 'clothing',
    'gender': 'men',
    'type': 'sustainable',
  },
  {
    'id': 6,
    'image': 'assets/images/s2.jpg',
    'brand': 'EcoStep',
    'title': 'Organic Slip-on Sneakers',
    'price': 2999,
    'original': 5999,
    'discount': '50% OFF',
    'category': 'footwear',
    'gender': 'men',
    'type': 'sustainable',
  },
  {
    'id': 7,
    'image': 'assets/images/a1.jpg',
    'brand': 'GreenTrend',
    'title': 'Upcycled Fabric Belt',
    'price': 1299,
    'original': 2599,
    'discount': '50% OFF',
    'category': 'accessories',
    'gender': 'men',
    'type': 'sustainable',
  },
  {
    'id': 8,
    'image': 'assets/images/c2.jpg',
    'brand': 'LuxeWear',
    'title': 'Silk Blend Blazer',
    'price': 11999,
    'original': 18999,
    'discount': '35% OFF',
    'category': 'clothing',
    'gender': 'men',
    'type': 'luxury',
  },
  {
    'id': 9,
    'image': 'assets/images/c3.jpg',
    'brand': 'LuxeLine',
    'title': 'Designer Wrap Skirt',
    'price': 9999,
    'original': 15999,
    'discount': '38% OFF',
    'category': 'clothing',
    'gender': 'women',
    'type': 'luxury',
  },
    {
    'id': 10,
    'image': 'assets/images/c3.jpg',
    'brand': 'LuxeLine',
    'title': 'Designer Wrap Skirt',
    'price': 9999,
    'original': 15999,
    'discount': '38% OFF',
    'category': 'clothing',
    'gender': 'women',
    'type': 'luxury',
  },
  {
    'id': 11,
    'image': 'assets/images/c2.jpg',
    'brand': 'LuxeWear',
    'title': 'Silk Blend Blazer',
    'price': 11999,
    'original': 18999,
    'discount': '35% OFF',
    'category': 'clothing',
    'gender': 'men',
    'type': 'luxury',
  },
  {
    'id': 12,
    'image': 'assets/images/a4.jpg',
    'brand': 'LuxeCharm',
    'title': 'Gold-Plated Hairpin Set',
    'price': 4999,
    'original': 7999,
    'discount': '38% OFF',
    'category': 'accessories',
    'gender': 'women',
    'type': 'luxury',
  },
];

List<Map<String, dynamic>> cartItems = [];

// Saved items from Game page
List<Map<String, String>> savedGameItems = [];